name: Angular CI/CD Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Define the jobs that will be run
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Use Node.js version 18.x

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies using npm
      - name: Install dependencies
        run: yarn install

      # Step 4: Run Angular unit tests
      - name: Run tests
        run: yarn test -- --watch=false --no-progress

      # Step 5: Build the Angular application
      - name: Build Angular app
        run: yarn build -- --configuration=production

      # Step 6: Upload production build as an artifact (optional, but useful for debugging)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: angular-build
          path: dist/

  # Optional: Deploy step (adjust to your needs)
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # You can add deployment steps here depending on where you want to deploy

      # Example Firebase deployment (replace with your actual Firebase deployment step)
      # - name: Install Firebase CLI
      #   run: npm install -g firebase-tools

      # - name: Deploy to Firebase
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      #   run: firebase deploy --only hosting

      # Example Netlify deployment (replace with your actual Netlify deployment step)
      # - name: Install Netlify CLI
      #   run: npm install -g netlify-cli

      # - name: Deploy to Netlify
      #   run: netlify deploy --prod --dir=dist/

      # Example AWS S3 deployment (replace with your actual AWS deployment step)
      # - name: AWS S3 Sync
      #   run: aws s3 sync dist/ s3://your-bucket-name --delete
